?start      : filtration
?filtration : filtration "h" num? -> max
            | filtration "в" num? -> max
            | filtration "l" num? -> min
            | filtration "н" num? -> min
            | dice
?dice       : num? "d" num        -> dice
            | num? "к" num        -> dice
            | num? "k" num        -> dice
            | num? "д" num        -> dice
?num        : NUMBER              -> to_int
%import common.NUMBER
%ignore " "