?start      : s_math

?s_math     : s_math "+" s_math         -> add
            | s_math "-" s_math         -> sub
            | h_math

?h_math     : h_math "*" h_math         -> mul
            | h_math "/" h_math         -> div
            | result
            | num

?result     : num                -> res

?num        : "(" s_math ")"
            | "[" s_math "]"
            | NUMBER                    -> to_int

%import common.NUMBER
%ignore " "