class Dice:

    def __init__(self, throw: int, face: int, retain_f: callable(list[int]) = None,
                 retain_n: int | None = None) -> None:
        self._result: None | list[int] = ...
        self._retain: None | list[int] = ...

        self._throw: int = ...
        self._face: int = ...
        self._retain_f: callable(list[int]) = ...
        self._retain_n: int = ...

    def __str__(self) -> str: ...

    def __repr__(self) -> str: ...

    @property
    def throw(self) -> int: ...

    @property
    def face(self) -> int: ...

    @property
    def retains(self) -> None | list[int]: ...

    @property
    def result(self) -> int | list[int]: ...

    @property
    def _all_result(self) -> list[int]: ...

    def _get_retains(self) -> None | list[int]: ...
